### ISSUE TITLE
能否开源各个任务的数据格式（demo）？

### ISSUE THREAD

**Issue by skykiseki** [clue-ai/PromptCLUE#13]
感谢能开源如此好用的模型，
直接索要数据这肯定是不可能的，但能否放出相应的数据格式提供用户拿自己数据进行FineTune参考？
比如v1.5新增的改写、纠错任务，thx

**Comment by joytianya** [comment]
可以参考readme里的改写、纠错任务示例格式，进行构建数据微调哈

**Comment by skykiseki** [comment]
> 可以参考readme里的改写、纠错任务示例格式，进行构建数据微调哈

好的，感谢，已经看到了，thx
